### ISSUE TITLE
Errors when compiling with clang.

### ISSUE THREAD

**Issue by jessechounard** [Madour/LDtkLoader#54]
I'm attempting to build with clang (v19.1.7, the version that comes with zig 0.14.0) and getting some compiler errors.

It appears it doesn't like the defaulted move assignment operator in `Entity`, `Enum`, `Layer`, and `World`. The errors look like this:

```
include/LDtkLoader/Enum.hpp:56:14: error: explicitly defaulted move assignment operator is implicitly deleted
```

Digging a little deeper into that, there's another line:
```
include/LDtkLoader/Enum.hpp:47:18: note: move assignment operator of 'Enum' is implicitly deleted because base class 'TagsContainer' has a deleted move assignment operator
```

And then:
```
include/LDtkLoader/containers/TagsContainer.hpp:22:40: note: copy assignment operator of 'TagsContainer' is implicitly deleted because field 'm_tags' has no copy assignment operator
```

If I comment out the default move assignment operators everything compiles and runs correctly. Do you think removing those could cause any problems?

**Comment by jessechounard** [comment]
Awesome, thank you for responding. (And for the library. It's great!)
